name: 🐞 Bug or error report
description: Report a suspected bug or error.
labels: ['🔍 needs triage', 'bug']

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug **only**.
      
      - All bug reports are welcome - we want to fix them!
      - This repo is maintained by volunteers. Please be courteous and patient as responses can take time. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
      - We accept pull requests. If you know how to fix it - go ahead! Fork the repo and submit a PR and we can take a look at it. 

      Please provide the following details about the issue you encountered. 

- type: textarea
  id: description
  attributes:
    label: Description
    description: Provide a short description of the issue you are facing.
    placeholder: Tell us in brief what is happening
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    description: Provide the steps you have taken so that we can reproduce the error.
    value: |
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected results
    description: Provide a description of what you expected to happen.
    placeholder: What should have happened
  validations:
    required: true

- type: textarea
  id: actual-results
  attributes:
    label: Actual Results
    description: Provide a description of what actually happens.
    placeholder: Tell us what you see
  validations:
    required: true

- type: dropdown
  id: component
  attributes:
      label: Solution component
      description: Let us know what component of the solution you are having trouble with.
      options:
      - Power App
      - Power Automate Flows
      - Deployment Script
      - Logic Apps
  validations:
      required: true

- type: dropdown
  id: os
  attributes:
      label: Operating system (environment)
      description: Provide the operating system that you are using to run the deployment script on.
      options:
        - Windows
        - Windows Server
        - macOS
        - Linux
        - Other
  validations:
      required: true

- type: textarea
  id: info
  attributes:
      label: Additional Info
      description: |
        Provide any additional information that may help with the identification of the root cause of this issue.
  validations:
      required: false
